#!/usr/bin/env python3

"""Provide a controllable full-duplex PTY endpoint for the integration test."""

import os
import pty
import signal
import time
import tty


running = True


def stop(_signum, _frame):
    global running
    running = False


signal.signal(signal.SIGTERM, stop)
signal.signal(signal.SIGINT, stop)

master, slave = pty.openpty()
tty.setraw(slave)
os.set_blocking(master, False)
os.symlink(os.ttyname(slave), "local")

draining = False
try:
    while running:
        if os.path.exists("inject"):
            marker = b"FULL_DUPLEX_RX_ALIVE\n"
            while marker:
                try:
                    written = os.write(master, marker)
                    if written == 0:
                        raise RuntimeError("PTY marker write made no progress")
                    marker = marker[written:]
                except BlockingIOError:
                    time.sleep(0.001)
            os.rename("inject", "injected")

        if os.path.exists("drain"):
            draining = True
            os.rename("drain", "draining")

        if draining:
            try:
                while os.read(master, 65536):
                    pass
            except BlockingIOError:
                pass

        time.sleep(0.001)
finally:
    os.close(master)
    os.close(slave)
    if os.path.lexists("local"):
        os.unlink("local")
